name: format

on:
  push:
    branches:
      - main
    paths:
      - '**.lua'

jobs:
  postprocessing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Format with Stylua
        uses: JohnnyMorganz/stylua-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          version: latest
          args: ./lua

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Format with stylua"
